import React from 'react';
import { useNavigate } from 'react-router-dom';
import { FaChevronDown } from "react-icons/fa";
import './HomePage.scss'
import JoinCTA from '../../components/JoinCTA/JoinCTA';

function HomePage() {
  const navigate = useNavigate();

  const handleScroll = () => {
    const target = document.getElementById('motivation');
    target?.scrollIntoView({behavior:'smooth'})
  }
  return (
    <>
      <div className="landing-section">
        <div className="landing-content">
          {/* Left Side */}
          <div className="landing-image">
            <img src="/SPHERE_Lab_Landing_Pic.webp" alt="SHPERE Lab" />
          </div>

          {/* Right Side */}
          <div className="landing-text">
            <h1 className="lab-name">The SPHERE Lab</h1>
            <h2 className="lab-title">
              Social Computing for Health and Well-being Research Laboratory
            </h2>
            <p className="lab-description">
              We are a research group in the Department of Biomedical
              Informatics (DBMI) at Vanderbilt University Medical Center
            </p>
            <button
              className="learn-more"
              onClick={() => navigate("/research")}
            >
              LEARN MORE
            </button>
          </div>
        </div>

        <div className="scroll-arrow" onClick={handleScroll}>
          <FaChevronDown />
        </div>
      </div>
      <div className="motivation-section" id="motivation">
        <div className="motivation-content">
          {/* Left Side */}
          <div className="motivation-image">
            <img src="/chipMotivationSection.jpg" alt="motivation-image" />
          </div>

          {/* Right Side */}
          <div className="motivation-text">
            <h4 className="motivation-heading">Our Motivation</h4>
            <h2 className="motivation-title">
              Center AI as a transformative force in medicine
            </h2>
            <p className="motivation-description">
              Our research is motivated by a vast amount of real-world data
              generated by people/machines in both online and offline
              environments. We believe that the data, or the evidence hidden in
              the data, is the key to understanding personal as well as public
              health and well-being. While new technologies have dramatically
              changed the world, the nature of social interaction and isolation
              of human beings is deemed to be a significant factor when decoding
              such evidence.
            </p>
          </div>
        </div>
      </div>

      <div className="mission-section" id="mission">
        <div className="mission-content">
          {/* Left Side */}
          <div className="mission-text">
            <img
              src="/OurMissionSmall.png"
              alt="Mission Icon"
              className="mission-icon"
            />
            <h4 className="mission-heading">Our Mission</h4>
            <h2 className="mission-title">
              Where Data Meets Compassionate Care
            </h2>
            <p className="mission-description">
              We aim to apply computational methods to the data that reside
              within/beyond electronic health records to tell stories that have
              strong implications for health-related behaviors, outcomes and
              policies. We will study the extent to which
              social/peer/professional support, as well as information
              system/technology, influences health and well-being in a
              long-term, dynamic, and collective manner.
            </p>
          </div>

          {/* Right Side */}
          <div className='mission-image'>
            <img src="/OurMissionMain.png" alt="Mission Main" />
          </div>
        </div>
      </div>

      <JoinCTA/>
    </>
  );
}

export default HomePage